### ISSUE TITLE
Error in plugin

### ISSUE THREAD

**Issue by NeoBlack** [PhileCMS/phileTemplateLex#1]
PHP Notice:  Undefined variable: twig_vars in /Users/franae/tmp/plugins/phile/templateLex/Classes/Template/Lex.php on line 80, referer: http://phile.dev.net/1.0.0/sub/page

I think this could not work, please check it

**Comment by Schlaefer** [comment]
Hi, thanks for the feedback. Alas nobody is maintaining this repository at the moment.

I close this issue as I mark this repository as abandoned and archived.
